import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ProcessBarProvider from "@/components/ProcessBarProvider";

const inter = Inter({ subsets: ["latin"] });

export const revalidate = 10;

export const metadata: Metadata = {
  title: "Truyện tranh ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ProcessBarProvider>
          <main className="min-h-screen bg-[rgb(38,50,56)] py-4">
            {children}
          </main>
        </ProcessBarProvider>
        <Footer />
      </body>
    </html>
  );
}
